generic/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('puzzles.urls')),
]

puzzles/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^puzzles/(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^users/(?P<user_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^login$', views.login_view, name='login'),
    url(r'^postlogin$', views.postlogin, name='postlogin'),
    url(r'^pay$', views.pay_view, name='pay'),
    url(r'^postpay$', views.postpay, name='postpay'),
    url(r'^logout$','django.contrib.auth.views.logout',{'next_page': '/'}, name='logout'),
    url(r'^signup$', views.signup, name='signup'),
]

puzzles/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Answer(models.Model):
    question = models.ForeignKey(Question)
    answer_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.answer_text


##### users #####
class UserProfile(models.Model):
    user = models.OneToOneField(User)

    rank = models.CharField(max_length=200)
    # install PIL for this to work
    #picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username

puzzles/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'first_name', 'last_name')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('rank',)

puzzles/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, render_to_response, redirect
from django.http import HttpResponse
from django.template import RequestContext, loader
from .models import Question, User
from .forms import UserForm, UserProfileForm


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    user = request.user
    context = {'latest_question_list': latest_question_list, 'user':user}
    return render(request, 'puzzles/index.html', context)

#### question detail ####
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    return render(request, 'puzzles/detail.html', {'question': question})

#### users profile####
def profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    userprofile = get_object_or_404(User, pk=user_id)
    team_members = [{'name':'Siti Mariam','id':0, 'remaining':45,'total':400}, {'name':'Kasturi Raju','id':1, 'remaining': 15,'total':350}, {'name':'Jessica Rajaratnam', 'id':2, 'remaining': 85,'total':300}, {'name':'Angel Widjojo', 'id':3, 'remaining':100,'total':250}, {'name':'Shana Salim', 'id':4, 'remaining':80,'total':530}]

    return render(request, 'puzzles/profile.html', {'user': user, 'userprofile':userprofile, 'team_members':team_members})


#### login / signup ####
def login_view(request):
    return render(request, 'puzzles/login.html')

def logout(request):
    logout(request)
    return redirect('index')

def postlogin(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
    return render(request, 'puzzles/index.html')

#### payment ####
def pay_view(request):
    return render(request, 'puzzles/pay.html')

def postpay(request):
    amount = request.POST['amount']
    return render(request, 'puzzles/thankyou.html')

def signup(request):
    context = RequestContext(request)
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            profile = profile_form.save(commit=False)
            profile.user = user

            ## Did the user provide a profile picture?
            ## If so, we need to get it from the input form and put it in the UserProfile model.
            #if 'picture' in request.FILES:
            #    profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True
            return redirect('index') 

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print user_form.errors, profile_form.errors

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render_to_response(
            'puzzles/signup.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered},
            context)

puzzles/templates/puzzles/base.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static "puzzles/css/style.css" %}">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.js" charset="utf-8"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<nav class="navbar navbar-inverse">
     <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src="/static/puzzles/images/logo.png" width='70em'></a>
        </div>
        <div class="collapse navbar-collapse " id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
              <li><a href="/users/{{request.user.id}}">{{request.user.first_name}}</a></li>
              <li><a href="/pay">Make payment</a></li>
              <li><a href="/logout">Logout</a></li>
            {% else %}
              <li><a href="/login">Login</a></li>
              <li><a href="/signup">Signup</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
</nav>



<div id='base-container'>
  {% block content %}(no content){% endblock %}
</div>

puzzles/templates/puzzles/detail.html
{% extends 'puzzles/base.html' %}
{% block content %}
<h2>{{ question.question_text }}</h2>


<ul>
{% for answer in question.answer_set.all %}
    <li>{{ answer.answer_text }}</li>
{% endfor %}
</ul>
{% endblock %}

puzzles/templates/puzzles/index.html
{% extends 'puzzles/base.html' %}
{% block content %}

<div id='main-container'>
  <div id='intro'>
    <img src="/static/puzzles/images/logo.png"><br>
    A loan of knowledge.
    <br>
    <img height="100em" src="/static/puzzles/images/Kiva_logo.png">
    <img height="100em" src="/static/puzzles/images/grameen.png">
  </div>
</div>
{% if latest_question_list %}
    <ul style='display:none;'>
    {% for question in latest_question_list %}
        <li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <!--p>Add some items</p-->
{% endif %}
<div id="bg">
  <img src="/static/puzzles/images/cover_photo.jpg">
</div>

{% endblock %}

puzzles/templates/puzzles/login.html
{% extends 'puzzles/base.html' %}
{% block content %}
<h1>Login</h1>
<form action="/postlogin" method="post">
    {% csrf_token %}
    <table>
    <tr>
      <td><label for="username">Username: </label></td>
      <td><input id="username" type="text" name="username" value=""></td>
    </tr>
    <tr>
      <td><label for="username">Password: </label></td>
      <td><input id="password" type="password" name="password" value=""></td>
    </tr>
    </table>
    <br>
    <input type="submit" value="OK">
</form>
{% endblock %}

puzzles/templates/puzzles/pay.html
{% extends 'puzzles/base.html' %}
{% block content %}
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="https://www.simplify.com/commerce/v1/simplify.js"></script>
<h1>Make a payment</h1>
<form action="/postpay" method="post">
    {% csrf_token %}
    <table>
    <tr>
      <td><label for="amount">Amount  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  LKR &nbsp; </label></td>
      <td><input id="amount" type="number" name="amount" value=""></td>
    </tr>
    <tr>
      <td><label>Card Number &nbsp;</label></td>
      <td><input id="cc-number" type="text" maxlength="20" autocomplete="off" value="" autofocus /></td>
    </tr>
    <tr>
      <td><label>CVC: </label></td>
      <td><input id="cc-cvc" type="text" maxlength="4" autocomplete="off" value=""/></td>
    </tr>
    </table>
        <label>Expiry Date: </label>
        <select id="cc-exp-month">
            <option value="01">Jan</option>
            <option value="02">Feb</option>
            <option value="03">Mar</option>
            <option value="04">Apr</option>
            <option value="05">May</option>
            <option value="06">Jun</option>
            <option value="07">Jul</option>
            <option value="08">Aug</option>
            <option value="09">Sep</option>
            <option value="10">Oct</option>
            <option value="11">Nov</option>
            <option value="12">Dec</option>
        </select>
        <select id="cc-exp-year">
            <option value="13">2013</option>
            <option value="14">2014</option>
            <option value="15">2015</option>
            <option value="16">2016</option>
            <option value="17">2017</option>
            <option value="18">2018</option>
            <option value="19">2019</option>
            <option value="20">2020</option>
            <option value="21">2021</option>
            <option value="22">2022</option>
        </select>
      </br>
    <br>
    <!--input type='image' width='130em;' src='/static/puzzles/images/masterpass.png'></input-->
    <br>
    <br>
    <input class='btn btn-small' type="submit" value="Submit payment">
    <img width='60em;' src='/static/puzzles/images/mastercard.png'>
</form>
    <br>
    <!--img width='60em;' src='/static/puzzles/images/simplify.png'-->

<!--form id="simplify-payment-form" action="" method="POST">
    <div>
        <label>Credit Card Number: </label>
        <input id="cc-number" type="text" maxlength="20" autocomplete="off" value="" autofocus />
    </div>
    <div>
        <label>CVC: </label>
        <input id="cc-cvc" type="text" maxlength="4" autocomplete="off" value=""/>
    </div>
    <div>
        <label>Expiry Date: </label>
        <select id="cc-exp-month">
            <option value="01">Jan</option>
            <option value="02">Feb</option>
            <option value="03">Mar</option>
            <option value="04">Apr</option>
            <option value="05">May</option>
            <option value="06">Jun</option>
            <option value="07">Jul</option>
            <option value="08">Aug</option>
            <option value="09">Sep</option>
            <option value="10">Oct</option>
            <option value="11">Nov</option>
            <option value="12">Dec</option>
        </select>
        <select id="cc-exp-year">
            <option value="13">2013</option>
            <option value="14">2014</option>
            <option value="15">2015</option>
            <option value="16">2016</option>
            <option value="17">2017</option>
            <option value="18">2018</option>
            <option value="19">2019</option>
            <option value="20">2020</option>
            <option value="21">2021</option>
            <option value="22">2022</option>
        </select>
    </div>
    <button id="process-payment-btn" type="submit">Process Payment</button>
    <div id="buy-with-masterpass-div"></div>
</form-->
<script>
$(document).ready(function() {
    $("#simplify-payment-form").on("submit", function() {
        // Disable the submit button
        $("#process-payment-btn").attr("disabled", "disabled");
        // Generate a card token & handle the response
        SimplifyCommerce.generateToken({
            key: "YOUR_PUBLIC_KEY",
            card: {
                number: $("#cc-number").val(),
                cvc: $("#cc-cvc").val(),
                expMonth: $("#cc-exp-month").val(),
                expYear: $("#cc-exp-year").val()
            }
        }, simplifyResponseHandler);
        // Prevent the form from submitting
        return false;
    });
    SimplifyCommerce.addMasterPassCheckoutButton("buy-with-masterpass-div", "YOUR_PUBLIC_KEY", masterPassResponseHandler,
        masterPassCanceledHandler);
});
</script>

{% endblock %}

puzzles/templates/puzzles/profile.html
{% extends 'puzzles/base.html' %}
{% block content %}
  <span style='font-size:2.7em;'>Welcome, {{user.first_name}}</span>
  <!--img width="150em" class='profilepic' src="/static/puzzles/images/profile_main.png"-->
  <br>
  <table>
    <tr>
    <td><img style='margin-top:1.5em;margin-left:6.1em;position:absolute;' width="100em" class='profilepic' src="/static/puzzles/images/profile_main.png">
    <canvas style='positive:absolute;' id="myChart"></canvas></td>
    <td>
       <b>Leader</b>
       <br><br>
       <span style='margin-left:-3em;'>$280 / $350 paid</span>
       <br>
       <br><button class='btn btn-small' style='margin-left:-3em;'><a href='/pay'>Make payment</a></button>
    </td>
  </tr></table>
  <br>
  <br>
  <span style='font-size:2.3em;'>Your team</span>
  <br>
  <span style='background-color:#33CC33;width:80em;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
  <br>
  <p><span style='font-size:1.3em;'>$710 / $1930 paid</span></p>
  <p><span style='font-size:1.1em;'>1.1% interest, $2000 limit</span><br>
  Next level: 0.8% interest, $2500 limit</p>
  <br>
  <br>
    <table class='table'>
    {% for k in team_members %}
      <tr style='position:relative;'>
       <td><img style='margin-top:1.5em;margin-left:2.3em;position:absolute;' width="100em" class='profilepic' src="/static/puzzles/images/profile{{ k.id }}.png">
       <canvas style='margin-left:-4em;positive:absolute;' id="myChart{{k.id}}"></canvas></td>
       <td><span style='font-size:1.4em;'>{{k.name}}</span>
       <br>${{k.total}}</td>
     </tr>
    {% endfor %}
    </table>
  <script>
    var data = [
      {
          value: 20,
          color:"#FFFFFF",
          highlight: "#FFFFFF",
          label: "Unpaid"
      },
      {
          value: 80,
          color:"#33CC33",
          highlight: "#33CC33",
          label: "Paid"
      },
      ]
    var options = [
          {
        animateScale: true
      }
    ]
    var ctx = document.getElementById("myChart").getContext("2d");
    var myNewChart = new Chart(ctx).Doughnut(data, options);
  {% for k in team_members %}
    var data = [
      {
          value: 100-{{ k.remaining }},
          color:"#FFFFFF",
          highlight: "#FFFFFF",
          label: "Unpaid"
      },
      {
          value: {{ k.remaining }},
          {% if k.remaining <= 50 %}
              color:"#F7464A",
          {% else %} 
              color:"#33CC33",
          {% endif %} 
          highlight: "#FFFFFF",
          label: "Paid"
      },
      ]
    var options = [
          {
        animateScale: true
      }
    ]
    var ctx = document.getElementById("myChart{{k.id}}").getContext("2d");
    var myNewChart = new Chart(ctx).Doughnut(data, options);
  {% endfor %}
  </script>
{% endblock %}

puzzles/templates/puzzles/signup.html
{% extends 'puzzles/base.html' %}
{% block content %}
    {% if registered %}
    <strong>Thank you for registering!</strong>
    <a href="/">Return to the homepage.</a><br />
    {% else %}
    <strong>Sign up here!</strong><br />

    <form id="user_form" method="post" action="/signup"
            enctype="multipart/form-data">

        {% csrf_token %}

        <!-- Display each form. The as_p method wraps each element in a paragraph
             (<p>) element. This ensures each element appears on a new line,
             making everything look neater. -->
        {{ user_form.as_p }}
        {{ profile_form.as_p }}

        <!-- Provide a button to click to submit the form. -->
        <input type="submit" name="submit" value="Signup" />
    </form>
    {% endif %}
{% endblock %}

puzzles/templates/puzzles/thankyou.html
{% extends 'puzzles/base.html' %}
{% block content %}
  <h1>Thank you</h1>
  <p>Your payment has been received, and your team stats have been updated!</p>
    <br>
    <img width='60em;' src='/static/puzzles/images/simplify.png'>
    <img width='60em;' src='/static/puzzles/images/mastercard.png'>

{% endblock %}